objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Suspend</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>(NOTE: The functionality of this field is replaced by the Action, Sub-Action and Fulfilment Status fields.) The desired provisioning action for the asset identified on this line item. Values include New (add), Active (no change), Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/VPLUpdateCartItems.cls
global with sharing class VPLUpdateCartItems implements vlocity_cmt.VlocityOpenInterface
{
global VPLUpdateCartItems() { }

    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        try
        {
            if (methodName.equals('updateresumeorders'))
            {
                updateresumeorders(inputMap,outMap,options);
            }
            else if(methodName.equals('updateOrderProduct'))
            {   
                updateOrderProduct(inputMap,outMap,options);
                
            }
            else{
                  result = false;
                 } 
        } 
        catch(Exception e)
        {
            System.debug('invokeMethod -> exception: '+e);
            result = false;
        }
        
        return result;
    }
    
    void updateresumeorders(Map<String, Object> inputMap, Map<String, Object> outMap,Map<String,Object> options)
    {
        String sOrderId = (String)inputMap.get('fdoId');
          List<OrderItem> updateOrderList = New List<OrderItem>();
          List<OrderItem>orderItemList = [Select Id,OrderId,vlocity_cmt__Action__c,OrderItem.Product2Id,OrderItem.Product2.Name,vlocity_cmt__ProvisioningStatus__c From OrderItem Where OrderId=: sOrderId];
        If(orderItemList != null && orderItemList.size() > 0)
          {
              for(OrderItem od:orderItemList)
              {
                  od.vlocity_cmt__Action__c = 'Resume';
                  od.vlocity_cmt__ProvisioningStatus__c = 'Resumed';
                  updateOrderList.add(od);
              }
              
              If(updateOrderList != null && updateOrderList.size() > 0)
              {
                  update updateOrderList;
              }
              
          }
    }
    
    void updateOrderProduct(Map<String, Object> inputMap, Map<String, Object> outMap,Map<String,Object> options)
    {
        String sOrderId = (String)inputMap.get('fdoId');
          List<OrderItem> updateOrderList = New List<OrderItem>();
          List<OrderItem>orderItemList = [Select Id,OrderId,vlocity_cmt__Action__c,OrderItem.Product2Id,OrderItem.Product2.Name,vlocity_cmt__ProvisioningStatus__c From OrderItem Where OrderId=: sOrderId];
        If(orderItemList != null && orderItemList.size() > 0)
          {
              for(OrderItem od:orderItemList)
              {
                  od.vlocity_cmt__Action__c = 'Suspend';
                  od.vlocity_cmt__ProvisioningStatus__c = 'Suspended';
                  updateOrderList.add(od);
              }
              
              If(updateOrderList != null && updateOrderList.size() > 0)
              {
                  update updateOrderList;
              }
              
          }
    }
      
}